# Maven

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: loadiumIntegration@1
  inputs:
    access_key: 'byA1U3RDtQYKGNOyXlFv'
    secret_key: 'LBbqqFECYcwWW59G2MMUxTHBuwgYME9L96Lqkrla'
    createTest: true
    test_name: 'isim'
    testType: 'JMX'
    jmeter_version: '5.0'
    region: 'eu-west-1'
    file_path: '$(System.DefaultWorkingDirectory)/dummy.jmx'
    additionalFile: false
    engine: '1'
    thread: '100'
    duration: '2'
    iteration: '-1'
    rampup: '10'